### ISSUE TITLE
Peer Review 3

### ISSUE THREAD

**Issue by absheth** [airavata-courses/Gateway-Falcons#74] opened 2019-04-04 00:12 UTC
Hello Team,

I have done the peer review and I found two issues as follows. 

1) When I checked all the pods in the Kubernetes dashboard, diet pod was not working. I think this is the same issue as #72
2) When I logged-in into the website, the main homepage was empty and continuously loading. I am not sure if it supposed to be empty or if it is fetching any information for that page.

Apart from these issues, I think everything is working properly.
1) When a pod was killed using Kube Monkey, I could see that another pod was spawned even before the original pod was terminated.
2) Also, the redesigned user interface is amazing.

Good work Team!

**Comment by Chirag-Galani** [comment] 2019-04-04 01:50
Hey Akash,
Thank you for your feedback. 
Regarding the issues, there is some API response glitch for the diet deployment and we are awaiting a fix in 24 hrs. Also, the front-end is still work-in-progress and the homepage is in our pipeline for the next milestone.

**Comment by Chirag-Galani** [comment] 2019-04-19 16:38
As mentioned on #72 the issue is fixed now. Also, the front page has been revamped

**Closed by Chirag-Galani** 2019-04-19 16:38 UTC
